environment:
  nodejs_version: "LTS"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g ionic cordova
  - npm install
  - node --version
  - npm --version

build_script:
  - npm run build
  - ionic cordova build --release android

test_script:
  - npm run lint

artifacts:
  - path: 'platforms\android\build\outputs\apk\*.apk'